### ISSUE TITLE
the config.json is missing.

### ISSUE THREAD

**Issue by eleander56-b** [Lobby-Hoes/tinder#2]
Wenn das config.json file sowas wie MongoDB URI oder so enthält ist es besser dies als Environment Variable zu setzten.
Für das deployment kannst du mir es auch per Discord schreiben, sodass ich die Env Variable setzen kann.

**Comment by eleander56-b** [comment]
Also sowas wie:

```
app.listen(port, () => {
    console.log(`Server is running at http://localhost:${port}`);

    const mongoUri = process.env.MONGO_URI;
    if (!mongoUri) {
        throw new Error('MONGO_URI environment variable is not set');
    }

    client = new MongoClient(mongoUri);
    client.connect()
        .then(() => {
            console.log('Connected to MongoDB');
        })
        .catch((err) => {
            console.error(err);
        });
});
```

**Comment by eleander56-b** [comment]
Wenn du willst kann ich mich aber auch die Tage hinsetzen und auf api.hobbylos.online ein Backend dafür bereitstellen.

**Comment by RedcodesDev** [comment]
Kann es heute Abend hinzufügen und ich schick dir dann die Connection URI per Discord. Lass uns mal bezüglich des Backends im Discord reden, weil ich denke das es aufgrund der Komplexität und Größe mehr Sinn machen würde, es in dem Projekt bereitzustellen.

**Comment by eleander56-b** [comment]
@RedcodesDev wunderbar
Ja können wir gerne machen :)

**Comment by RedcodesDev** [comment]
`MONGO_URI` environment variable hinzugefügt

https://github.com/Lobby-Hoes/tinder/commit/6769b7a06dcda1b06101f1e8b4da5f1ffadbb91d
